from __future__ import annotations

import json
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

from .tools import ToolRegistry


TS_SHIM = r'''// Generated by pi-python-harness. Keep per-tool logic in Python.
import { readFileSync } from "node:fs";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

type ToolManifest = {
  version: number;
  tools: Array<{
    name: string;
    label: string;
    description: string;
    parameters: Record<string, unknown>;
    promptSnippet?: string;
    promptGuidelines?: string[];
    executionMode?: "sequential" | "parallel";
  }>;
};

type BridgeRecord =
  | { type: "update"; result: any }
  | { type: "result"; result: any }
  | { type: "error"; message: string };

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is required for pi-python-harness`);
  return value;
}

async function readNdjson(response: Response, onRecord: (record: BridgeRecord) => void): Promise<void> {
  const body = response.body;
  if (!body) return;
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  const flushLines = (final: boolean) => {
    while (true) {
      const idx = buffer.indexOf("\n");
      if (idx < 0) break;
      let line = buffer.slice(0, idx);
      buffer = buffer.slice(idx + 1);
      if (line.endsWith("\r")) line = line.slice(0, -1);
      if (line.trim().length > 0) onRecord(JSON.parse(line) as BridgeRecord);
    }
    if (final && buffer.trim().length > 0) {
      onRecord(JSON.parse(buffer) as BridgeRecord);
      buffer = "";
    }
  };

  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    flushLines(false);
  }
  buffer += decoder.decode();
  flushLines(true);
}

async function executeViaPythonBridge(
  bridgeUrl: string,
  token: string,
  toolName: string,
  toolCallId: string,
  params: unknown,
  signal: AbortSignal | undefined,
  onUpdate: ((result: any) => void) | undefined,
  ctx: any,
): Promise<any> {
  const payload = {
    toolName,
    toolCallId,
    arguments: params ?? {},
    cwd: ctx?.cwd,
    context: {
      hasUI: Boolean(ctx?.hasUI),
      model: ctx?.model ? { provider: ctx.model.provider, id: ctx.model.id, name: ctx.model.name } : null,
    },
  };

  const response = await fetch(`${bridgeUrl}/execute`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Pi-Python-Token": token,
    },
    body: JSON.stringify(payload),
    signal,
  });

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(`Python bridge returned ${response.status}: ${text}`);
  }

  let finalResult: any | undefined;
  await readNdjson(response, (record) => {
    if (record.type === "update") {
      onUpdate?.(record.result);
    } else if (record.type === "result") {
      finalResult = record.result;
    } else if (record.type === "error") {
      throw new Error(record.message);
    }
  });

  if (finalResult === undefined) {
    throw new Error(`Python bridge returned no final result for ${toolName}`);
  }
  return finalResult;
}

export default function(pi: ExtensionAPI) {
  const manifestPath = requireEnv("PI_PY_TOOL_MANIFEST");
  const bridgeUrl = requireEnv("PI_PY_TOOL_BRIDGE_URL");
  const token = requireEnv("PI_PY_TOOL_BRIDGE_TOKEN");
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as ToolManifest;

  for (const tool of manifest.tools) {
    pi.registerTool({
      name: tool.name,
      label: tool.label,
      description: tool.description,
      promptSnippet: tool.promptSnippet,
      promptGuidelines: tool.promptGuidelines,
      parameters: tool.parameters as any,
      executionMode: tool.executionMode,
      async execute(toolCallId, params, signal, onUpdate, ctx) {
        return await executeViaPythonBridge(bridgeUrl, token, tool.name, toolCallId, params, signal, onUpdate, ctx);
      },
    });
  }

  pi.on("session_shutdown", async () => {
    try {
      await fetch(`${bridgeUrl}/session_shutdown`, {
        method: "POST",
        headers: { "X-Pi-Python-Token": token },
      });
    } catch {
      // Shutdown should not make Pi fail.
    }
  });
}
'''


@dataclass(frozen=True)
class GeneratedShim:
    directory: Path
    manifest_path: Path
    extension_path: Path
    env: Mapping[str, str]


def write_generated_shim(
    registry: ToolRegistry,
    *,
    bridge_url: str,
    token: str,
    directory: str | Path | None = None,
) -> GeneratedShim:
    base = Path(directory) if directory is not None else Path(tempfile.mkdtemp(prefix="pi-python-harness-"))
    base.mkdir(parents=True, exist_ok=True)
    manifest_path = base / "python-tools.manifest.json"
    extension_path = base / "python-tools.pi-extension.ts"

    manifest_path.write_text(json.dumps(registry.manifest(), ensure_ascii=False, indent=2), encoding="utf-8")
    extension_path.write_text(TS_SHIM, encoding="utf-8")

    return GeneratedShim(
        directory=base,
        manifest_path=manifest_path,
        extension_path=extension_path,
        env={
            "PI_PY_TOOL_MANIFEST": str(manifest_path),
            "PI_PY_TOOL_BRIDGE_URL": bridge_url,
            "PI_PY_TOOL_BRIDGE_TOKEN": token,
        },
    )
